name: schedule-deploy

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    env:
      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
