name: Unit Tests

on: [push, pull_request]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Run Unit Tests
      run: npm test

  run-cypress-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove husky folder
        run: rm -rf .husky

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run start
          browser: chrome
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}